### ISSUE TITLE
ログイン処理（しょり）の追加（ついか）要望（ようぼう）

### ISSUE THREAD

**Issue by yoshi-koyama** [ZarLiHninn/springCustom_Login#4]
## ログイン前（まえ）
localhost:8080/にアクセスしてもログイン画面（がめん）に遷移（せんい）する。 -> OK

## ログイン後（ご）
存在（そんざい）しないパスを指定（してい）すると404.html（page not found）を表示（ひょうじ）する。

404.htmlが表示（ひょうじ）されたあともログイン情報（じょうほう）は保持（ほじ）する。

一度（いちど）に保持（ほじ）できるセッションは１つだけです。
もし多重（たじゅう）ログインがあった場合、後勝ち（あとがち）とする。

## ログアウト後（ご）
ログアウト処理（しょり）をした後（あと）に localhost:8080/ にアクセスしてもlogin.htmlが表示（ひょうじ）されるようにしたい。

**Comment by yoshi-koyama** [comment]
こちらの対応（たいおう）をするときに、

topic/login-enhance

というブランチをつくってください。

そして、masterブランチへのPull Requestをつくり、@yoshi-koyama にリンクを送って（おくって）ください。

注意（ちゅうい）：masterブランチに直接（ちょくせつ）プッシュしないように気をつけてね。

**Comment by yoshi-koyama** [comment]
@ZarLiHninn 
すべてを一回でやらずに1つできたらプルリクエストあげてくれて大丈夫ですよ。

**Comment by ZarLiHninn** [comment]
はい。そうします。
